// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var CATALOG = [
  {
    category: "Data Center Services",
    services: [
      "Dedicated Servers",
      "VPS",
      "Application Hosting",
      "Database Hosting",
      "Storage Provisioning",
      "Backup and DR",
      "Connectivity & CDN"
    ]
  },
  {
    category: "Hosting Services",
    services: ["Domain Registration", "Web Hosting", "App Development", "Business Email Accounts"]
  },
  {
    category: "IT Infrastructure",
    services: ["IT Managed Services", "Consulting and Migration", "Hardware Support"]
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List WularData services",
  description: "List the WularData service catalogue, optionally filtered to one category.",
  inputSchema: {
    category: z.enum(["Data Center Services", "Hosting Services", "IT Infrastructure"]).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? CATALOG.filter((c) => c.category === category) : CATALOG;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { categories: items }
    };
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-quotes.ts
var list_quotes_default = defineTool2({
  name: "list_quotes",
  title: "List my quote requests",
  description: "List the signed-in user's WularData quote requests, newest first.",
  inputSchema: {
    status: z2.enum(["new", "in_review", "quoted", "closed"]).optional().describe("Optional status filter."),
    limit: z2.number().int().min(1).max(50).default(20).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("quote_requests").select("id, service_category, service_name, company, contact_name, email, phone, message, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-quote-request.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_quote_request_default = defineTool3({
  name: "create_quote_request",
  title: "Create a quote request",
  description: "Create a new WularData quote request for the signed-in user.",
  inputSchema: {
    service_category: z3.enum(["Data Center Services", "Hosting Services", "IT Infrastructure"]).describe("Top-level service category."),
    service_name: z3.string().trim().min(2).max(150).describe("Service the quote is for, e.g. 'VPS'."),
    contact_name: z3.string().trim().min(2).max(100).describe("Contact person's name."),
    email: z3.string().trim().email().max(255).describe("Contact email address."),
    company: z3.string().trim().max(150).optional().describe("Company name."),
    phone: z3.string().trim().max(30).optional().describe("Contact phone number."),
    message: z3.string().trim().max(2e3).optional().describe("Requirements and details.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("quote_requests").insert({ ...input, user_id: ctx.getUserId() }).select("id, service_category, service_name, status, created_at");
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}, null, 2) }],
      structuredContent: { quote: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/list-tickets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_tickets_default = defineTool4({
  name: "list_tickets",
  title: "List my support tickets",
  description: "List the signed-in user's WularData support tickets, newest first.",
  inputSchema: {
    status: z4.enum(["open", "pending", "resolved", "closed"]).optional().describe("Optional status filter."),
    limit: z4.number().int().min(1).max(50).default(20).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("support_tickets").select("id, subject, service, priority, status, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-ticket.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var create_ticket_default = defineTool5({
  name: "create_ticket",
  title: "Create a support ticket",
  description: "Open a new WularData support ticket for the signed-in user, with an optional first message.",
  inputSchema: {
    subject: z5.string().trim().min(3).max(200).describe("Short summary of the issue."),
    service: z5.string().trim().max(150).optional().describe("Affected service, e.g. 'Dedicated Servers'."),
    priority: z5.enum(["low", "normal", "high", "urgent"]).default("normal").describe("Ticket priority."),
    body: z5.string().trim().max(4e3).optional().describe("First message describing the issue.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ subject, service, priority, body }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("support_tickets").insert({ user_id: userId, subject, service, priority: priority ?? "normal" }).select("id, subject, service, priority, status, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ticket = data?.[0];
    if (ticket && body) {
      const { error: msgError } = await supabase.from("ticket_messages").insert({ ticket_id: ticket.id, sender_id: userId, body });
      if (msgError) {
        return {
          content: [
            { type: "text", text: `Ticket ${ticket.id} created, but the first message failed: ${msgError.message}` }
          ],
          isError: true
        };
      }
    }
    return {
      content: [{ type: "text", text: JSON.stringify(ticket ?? {}, null, 2) }],
      structuredContent: { ticket }
    };
  }
});

// src/lib/mcp/tools/reply-to-ticket.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var reply_to_ticket_default = defineTool6({
  name: "reply_to_ticket",
  title: "Reply to a support ticket",
  description: "Post a message on one of the signed-in user's WularData support tickets.",
  inputSchema: {
    ticket_id: z6.string().uuid().describe("ID of the ticket to reply to."),
    body: z6.string().trim().min(1).max(4e3).describe("Message text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ ticket_id, body }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ticket_messages").insert({ ticket_id, sender_id: ctx.getUserId(), body }).select("id, ticket_id, body, created_at");
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}, null, 2) }],
      structuredContent: { message: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/get-ticket-messages.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^3.25.76";
var get_ticket_messages_default = defineTool7({
  name: "get_ticket_messages",
  title: "Read a ticket conversation",
  description: "Read the message thread of one of the signed-in user's WularData support tickets.",
  inputSchema: {
    ticket_id: z7.string().uuid().describe("ID of the ticket.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ticket_messages").select("id, sender_id, body, created_at").eq("ticket_id", ticket_id).order("created_at", { ascending: true });
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_profile_default = defineTool8({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in user's WularData customer profile details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, full_name, company, phone, country, created_at").eq("id", ctx.getUserId()).maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [
        {
          type: "text",
          text: JSON.stringify({ email: ctx.getUserEmail(), ...data ?? {} }, null, 2)
        }
      ],
      structuredContent: { profile: { email: ctx.getUserEmail(), ...data ?? {} } }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rrdkrfxspqhyjbfrsoff";
var mcp_default = defineMcp({
  name: "ovh-insights-report",
  title: "OVH Insights Report",
  version: "0.1.0",
  instructions: "Tools for the WularData customer portal. Browse the service catalogue with `list_services`, manage quote requests with `list_quotes` and `create_quote_request`, and handle support with `list_tickets`, `create_ticket`, `get_ticket_messages` and `reply_to_ticket`. `get_profile` returns the signed-in customer's details. All data tools act as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_services_default,
    list_quotes_default,
    create_quote_request_default,
    list_tickets_default,
    create_ticket_default,
    get_ticket_messages_default,
    reply_to_ticket_default,
    get_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
